### ISSUE TITLE
Hyper error: invalid certificate: UnknownIssuer

### ISSUE THREAD

**Issue by povilasv** [databricks/click#109]
```
[dev-telecom] [none] [none] > pods
No update command specified, can't update
Couldn't get an authentication token. You can try exiting Click and running a kubectl command against the cluster to refresh it. Also please report this error on the Click github page.
Hyper error: invalid certificate: UnknownIssuer
```

```
kubectl get pods --context dev-telecom
NAME                                                              READY   STATUS             RESTARTS   AGE
alertmanager-55448f5d7-85s2s                                      2/2     Running            0          2d1h
...
```

Kube config

```

- cluster:
    certificate-authority: PATH_TO_CA.PEM
    server: https://SERVER
  name: dev
- context:
    cluster: dev
    namespace: telecom
    user: USER
  name: dev-telecom

```
