### ISSUE TITLE
 OpenID Connect support

### ISSUE THREAD

**Issue by rcny** [databricks/click#118]
Hello!

Just stumbled upon this really amazing tool, but it's impossible for me to use it in my daily job routines because of lack of the OIDC authn. Is there any possibility for this authn strategy to appear in Click in the foreseeable future?

```
[some-context] [some-ns] [none] > nodes
No update command specified, can't update
Couldn't get an authentication token. You can try exiting Click and running a kubectl command against the cluster to refresh it. Also please report this error on the Click github page.
Server Error: nodes is forbidden: User "system:anonymous" cannot list resource "nodes" in API group "" at the cluster scope
```

User configuration from my kubeconfig file (values were edited):
```
- name: mrcat
  user:
    auth-provider:
      config:
        client-id: blah
        client-secret: wow
        id-token: blah
        idp-certificate-authority-data: wow
        idp-issuer-url: https://blah
        refresh-token: wow
      name: oidc
```
