### ISSUE TITLE
Context has no client certificate and key

### ISSUE THREAD

**Issue by tombh** [databricks/click#127]
Just trying out this for the first time. `kubectl` works fine on all my contexts. The full warning is:

`Context xxxxxxx has no client certificate and key, nor does it specify any auth method (user/pass, token, auth-provider).  You will likely not be able to authenticate to this cluster.  Please check your kube config.`

I don't know what to do?

**Comment by nicklan** [comment]
Do you know what kind of authentication your k8s cluster uses? It's possible it's something click doesn't support yet.

If you could post your `~/.kube/config` (with anything private redacted of course) that would be helpful.

**Comment by tombh** [comment]
This is the basic idea:
```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: 
    server: https://xxx.k8s.ondigitalocean.com
  name: do-sfo2-xxx
- cluster:
    ...
contexts:
- context:
    cluster: do-sfo2-xxx
    user: do-sfo2-xxx-admin
  name: do-sfo2-xxx
...
current-context: do-sfo2-xxx
kind: Config
preferences: {}
users:
- name: ci_user
  user:
    token: |-
      Name:         ci-token-2nmqd
      Namespace:    default
      Labels:       <none>
      Annotations:  kubernetes.io/service-account.name: ci
                    kubernetes.io/service-account.uid: xxxx

      Type:  kubernetes.io/service-account-token

      Data
      ====
      ca.crt:     1156 bytes
      namespace:  7 bytes
      token:      xxxxx
- name: do-sfo2-xxx-admin
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - kubernetes
      - cluster
      - kubeconfig
      - exec-credential
      - --version=v1beta1
      - --context=default
      - xxxxx
      command: doctl
      env: null
...
```

I don't think the `ci_user` is really relevant though. There are a lot more contexts and users, but I've just skipped them for clarity.
