### ISSUE TITLE
Invalid certificate or key data when selecting context

### ISSUE THREAD

**Issue by lbolla** [databricks/click#29]
```
[none] [none] [none] > ctx ldc
Private key data was invalid: ()
[Warning] Couldn't find/load context ldc, now no current context.  Error: Failed to get config: Invalid certificate or key data for context: ldc
```
When using `kubectl config use-context` all works fine.

**Comment by mbovo** [comment]
Same issue here

**Comment by Ljzn** [comment]
my issue:
```
[Warning] Couldn't find/load context gke_inblockchain-back-garden_asia-east1-a_cluster-1, now no current context.  Error: Failed to get config: Invalid context gke_inblockchain-back-garden_asia-east1-a_cluster-1.  Each user must have either a token, a username AND password, or a client-certificate AND a client-key.
```

**Comment by den-is** [comment]
same here two local on prem. clusters
kubectl kube-shell etc are working just fine
```
kubectl config view
apiVersion: v1
clusters:
- cluster:
    server: ""
  name: ""
- cluster:
    certificate-authority-data: REDACTED
    server: https://10.66.150.42:6443
  name: devk8s
- cluster:
    certificate-authority-data: REDACTED
    server: https://10.55.11.104:6443
  name: sandbox
contexts:
- context:
    cluster: sandbox
    user: superadmin
  name: default
- context:
    cluster: devk8s
    user: admin@devk8s
  name: mydev
current-context: mydev
kind: Config
preferences: {}
users:
- name: admin@devk8s
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
- name: superadmin
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
```
