### ISSUE TITLE
Hyper error: invalid certificate: InvalidReferenceName

### ISSUE THREAD

**Issue by t0mmyt** [databricks/click#45]
I'm getting this error using a cluster spun up with kubespray and using tls certificates for auth.

```[development] [defualt] [none] > pods
Hyper error: invalid certificate: InvalidReferenceName
```

.kube/config looks like the following:
```
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    server: https://172.17.8.101:6443
    certificate-authority: /home/tom/.kube/ca-development.pem
  name: development

users:
- name: development-admin
  user:
    client-certificate: /home/tom/.kube/admin-.pem
    client-key: /home/tom/.kube/admin-key.pem
    
contexts:
- context:
    cluster: development
    user: development-admin
  name: development

current-context: development
```
I've tried adding ```insecure-skip-tls-verify: true``` to the user but it has no effect.  kubectl works fine without error.  Masters are k8s v1.9.2
