### ISSUE TITLE
Cannot access AKS cluster with RBAC enabled

### ISSUE THREAD

**Issue by maximbaz** [databricks/click#81]
Hi there,

I wanted to try your project on my AKS cluster, but I cannot select anything except context due to missing access.

```
[none] [none] [none] > context dev
[dev] [none] [none] > pods
Server Error: pods is forbidden: User "clusterUser" cannot list pods at the cluster scope
```

Here's my `~/.kube/config` file:

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: XXXX
    server: https://XXX:443
  name: dev
contexts:
- context:
    cluster: dev
    user: clusterUser_dev
  name: dev
current-context: dev
kind: Config
preferences: {}
users:
- name: clusterUser_dev
  user:
    client-certificate-data: XXX
    client-key-data: XXX
    token: XXX
```
